const express = require('express')
const { createUser, loginUser, getallUser, getaUser, deleteaUser, updateaUser, handleRefreshToken, logout, userCart, getUserCart, findNearestCSD } = require('../controller/userCtrl')
const { authMiddleware, isAdmin } = require('../middlewares/authMiddleware')
const router = express.Router()
router.post('/register', createUser)
router.post('/login', loginUser)
router.get('/nearestCSD', findNearestCSD)
router.post('/cart', authMiddleware, isAdmin, userCart)
router.get('/all-users', getallUser)
router.get('/refresh', handleRefreshToken)
router.get('/logout', logout)
router.get('/cart', authMiddleware, isAdmin, getUserCart)
router.get('/:id', authMiddleware, isAdmin, getaUser)
router.delete('/:id', authMiddleware, isAdmin, deleteaUser)
router.put('/edit-user', authMiddleware, updateaUser)
module.exports = router